###1.
dryrun: N
###2. The path to store the direct results. Please finish with the "/". Can replace the following with a absolute path.
output_path: ./
#output_path: /home/khu/Desktop/project_2/AMR_codes/pipeline_model/trained/
###3. The path to store the temporary files. Please finish with the "/". Can replace the following with a absolute path.
#log_path: /home/khu/Desktop/project_2/AMR_codes/pipeline_model/trained/
log_path: ./
###4 . max cpu
n_jobs: 2

### 5. Phylogeny background. Can be one of: close, low_similarity, distant_phylo,
### each indicating the degree of phylogeny/sequence similarity relationship between your sample and genomes used in this study.
### close means high similarity or low phylogeny divergence, low_similarity means low similarity, distant_phylo means high phylogeny divergence.
folds_setting: close

### 6. Software. Can be one or multiple (separated by ",") of: PhenotypeSeeker, Kover, ResFinder
Software: Kover, ResFinder

###7. Env:
main_env: snakemake_env

